language: generic
sudo: true

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libpcap-dev
            - make
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libpcap-dev
            - make
          sources: *sources

branches:
  only:
    - master
    - dev*

script: make

#todo test bin/tool --help
#https://gist.github.com/nabijaczleweli/e53219d037c4ccb34f3c
