version: 1.0.{build}

environment:
  matrix:
    - compiler: mingw32
    - compiler: mingw-w64
    - compiler: vs2015
      platform: x86
      config: Debug
    - compiler: vs2015
      platform: x86
      config: Release
    - compiler: vs2015
      platform: x64
      config: Debug
    - compiler: vs2015
      platform: x64
      config: Release

install:
- appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-0.1.zip
- 7z x .\npcap-sdk-0.1.zip -o.\libs\npcap-sdk\

before_build:

build_script:
- if "%compiler%"=="mingw32" mingw32-make all
- if "%compiler%"=="mingw-w64" mingw32-make all
- if "%compiler%"=="vs2015" powershell -command "msbuild win32\BP.sln /p:Configuration=%config% /p:Platform=%platform%"
