#Inspired by https://github.com/seladb/PcapPlusPlus/blob/master/appveyor.yml
version: 1.0.{build}

environment:
  matrix:
    - compiler: vs2015
      platform: x86
      config: Debug
    - compiler: vs2015
      platform: x86
      config: Release
    - compiler: vs2015
      platform: x64
      config: Debug
    - compiler: vs2015
      platform: x64
      config: Release

install:
- appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-0.1.zip
- 7z x .\npcap-sdk-0.1.zip -o.\libs\

before_build:
- cd libs\
- ren npcap-sdk-0.1 npcap-sdk
- cd ..

build_script:
- if "%compiler%"=="vs2015" powershell -command "msbuild win32\namon.sln /p:Configuration=%config% /p:Platform=%platform%"
